package com.payflowx.order.constant;

public enum ErrorCode {
    ORDER_NOT_FOUND,
    DUPLICATE_RECEIPT,
    INVALID_ORDER_AMOUNT,
    ORDER_ALREADY_PAID,
    ORDER_EXPIRED,
    ORDER_CANCELLED,
    ORDER_ALREADY_CANCELLED,
    ORDER_STATUS_INVALID,
    MERCHANT_NOT_FOUND,
    MERCHANT_NOT_ACTIVE,
    MERCHANT_KYC_NOT_VERIFIED,
    INVALID_REQUEST,
    INTERNAL_ERROR,
}