apiVersion: apps/v1
kind: Deployment

metadata:
  name: settlement-service
  namespace: payflowx

spec:
  replicas: 1

  selector:
    matchLabels:
      app: settlement-service

  template:
    metadata:
      labels:
        app: settlement-service

    spec:
      containers:
        - name: settlement-service
          image: ghcr.io/rahu0909/settlement-service:latest

          ports:
            - containerPort: 8086
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"

            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: EUREKA_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: payflowx-config
                  key: EUREKA_SERVER_URL