package com.payflowx.user.constant;

public enum ErrorCode {
    USER_NOT_FOUND,
    USER_ACCOUNT_NOT_ACTIVE,
    USER_DEACTIVATED,

    KYC_NOT_FOUND,
    KYC_NOT_VERIFIED,
    KYC_ALREADY_VERIFIED,
    KYC_ALREADY_APPROVED,
    KYC_ALREADY_REJECTED,
    KYC_REJECTED_RESUBMIT_REQUIRED,

    PROFILE_LOCKED_KYC,
    INVALID_DOB,
    INVALID_AVATAR_URL,
    UNDERAGE,


    ADDRESS_NOT_FOUND,
    DEFAULT_ADDRESS_NOT_FOUND,
    ADDRESS_LIMIT_EXCEEDED,

    STATUS_ALREADY_SET,
    BLOCKED_USER_MUST_BE_SUSPENDED_FIRST,

    ONBOARDING_INCOMPLETE,
    DEFAULT_ADDRESS_REQUIRED,

    INVALID_REQUEST
}