apiVersion: v1
kind: Service

metadata:
  name: notification-service
  namespace: payflowx

spec:
  selector:
    app: notification-service

  ports:
    - port: 8087
      targetPort: 8087

  type: ClusterIP