package com.payflowx.settlement.constant;

public enum ErrorCode {

    INTERNAL_SERVER_ERROR,

    INVALID_REQUEST,

    MERCHANT_BALANCE_NOT_FOUND,

    SETTLEMENT_NOT_FOUND,

    INVALID_SETTLEMENT_STATE,

    INSUFFICIENT_AVAILABLE_BALANCE,

    DUPLICATE_SETTLEMENT,

    INVALID_SETTLEMENT_AMOUNT,
    PAYMENT_NOT_FOUND,
    INSUFFICIENT_RESERVED_BALANCE
}