apiVersion: v1
kind: ConfigMap

metadata:
  name: payflowx-config
  namespace: payflowx

data:
  EUREKA_SERVER_URL: "http://discovery-server:8761/eureka/"
  ZIPKIN_URL: "http://zipkin:9411"
  RABBITMQ_HOST: "rabbitmq"
  DB_HOST: "postgres"
  DB_PORT: "5432"