package com.payflowx.notification.enums;

public enum ErrorCode {

    INTERNAL_SERVER_ERROR,
    VALIDATION_ERROR,
    RESOURCE_NOT_FOUND,
    NOTIFICATION_FAILED,
    INVALID_REQUEST,
    MERCHANT_SERVICE_UNAVAILABLE,
    WEBHOOK_DELIVERY_FAILED
}