package com.payflowx.notification.enums;

public enum NotificationEventType {

    MERCHANT_KYC_APPROVED,

    MERCHANT_KYC_REJECTED,

    PAYMENT_COMPLETED,

    PAYMENT_FAILED,

    REFUND_PROCESSED,

    PAYOUT_SUCCESS,

    PAYOUT_FAILED,

    SETTLEMENT_COMPLETED,

    PASSWORD_RESET,

    USER_REGISTERED,

    PAYMENT_CREATED,
    PAYMENT_PROCESSING,
    PAYMENT_SUCCESS,

    REFUND_CREATED,
    REFUND_SUCCESS,
    REFUND_FAILED,
    SETTLEMENT_CREATED,
    SETTLEMENT_FAILED,
    PAYOUT_CREATED,
    PAYOUT_REVERSED
}