apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway
  namespace: payflowx

spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      containers:
        - name: api-gateway
          image: ghcr.io/rahu0909/api-gateway:latest

          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"

            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: EUREKA_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: payflowx-config
                  key: EUREKA_SERVER_URL