server:
  port: 8085

spring:
  application:
    name: payment-service

  profiles:
    active: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jackson:
    time-zone: UTC

  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000
            loggerLevel: basic
      httpclient:
        hc5:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

  instance:
    prefer-ip-address: true
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    root: INFO
    com.payflowx.payment: DEBUG


payment:
  events:
    batch-size: 100
    retry-threshold: 5