{
 "title": "Merchant Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Merchant Approval %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(merchants_approved_total / merchants_total) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rejected Merchants",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "merchants_rejected_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Approved Merchants",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "merchants_approved_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Merchants",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "merchants_total", "legendFormat": "__auto" }
   ]
  }
 ]
}