{
 "title": "Notification Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Delivery Success %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\nnotifications_sent_total\r\n/\r\n(\r\nnotifications_sent_total +\r\nnotifications_failed_total\r\n)\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Webhook Notifications",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "webhook_notifications_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Email Notifications",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "email_notifications_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Notifications Failed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "notifications_failed_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Notifications Sent",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "notifications_sent_total", "legendFormat": "__auto" }
   ]
  }
 ]
}