{
 "title": "Payment Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Payment Success Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(payments_processed_total /\r\n(payments_processed_total + payments_failed_total)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payments Refunded",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "payments_refunded_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Payments Failed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "payments_failed_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Payments Processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "payments_processed_total", "legendFormat": "__auto" }
   ]
  }
 ]
}