server:
  port: 8084

spring:
  application:
    name: order-service

  profiles:
    active: local

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  jpa:
    hibernate:
      ddl-auto: update

resilience4j:
  circuitbreaker:
    instances:

      merchantService:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s

      rabbitPublisher:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s

  retry:
    instances:

      merchantService:
        maxAttempts: 3
        waitDuration: 1s

      rabbitPublisher:
        maxAttempts: 3
        waitDuration: 2s

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

  instance:
    prefer-ip-address: true
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}

  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
    com.payflowx.order: DEBUG