package com.payflowx.merchant.constant;

public enum ErrorCode {

    // Merchant
    MERCHANT_NOT_FOUND,
    MERCHANT_ALREADY_EXISTS,
    MERCHANT_NOT_ACTIVE,
    MERCHANT_BLOCKED,
    MERCHANT_SUSPENDED,
    MERCHANT_DEACTIVATED,

    // KYC
    KYC_NOT_FOUND,
    KYC_NOT_VERIFIED,
    KYC_ALREADY_VERIFIED,
    KYC_ALREADY_APPROVED,
    KYC_ALREADY_REJECTED,

    // API KEY
    API_KEY_INVALID,
    API_KEY_REVOKED,

    // Generic
    INVALID_REQUEST,
    INTERNAL_ERROR,

    STATUS_ALREADY_SET,
    BLOCKED_MERCHANT_MUST_BE_SUSPENDED_FIRST,

    API_KEY_NOT_FOUND,
    INVALID_API_KEY,
    MAX_API_KEYS_LIMIT_REACHED,

    WEBHOOK_NOT_FOUND,
    INVALID_WEBHOOK_URL,
    WEBHOOK_LIMIT_EXCEEDED,
    MERCHANT_KYC_NOT_FOUND,
    MERCHANT_KYC_NOT_VERIFIED
}