server:
  port: 8080

spring:
  application:
    name: api-gateway

  profiles:
    active: local

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cloud:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
    gateway:
      routes:
        # ===============================
        # Eureka Dashboard UI
        # ===============================
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
          filters:
            - SetPath=/
        - id: eureka-sever-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        # ===============================
        # Auth Service Routes
        # ===============================
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        # ===============================
        # User Service Routes
        # ===============================
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,gateway

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    instance:
      prefer-ip-address: true
  instance:
    prefer-ip-address: true
    hostname: localhost

app:
  jwt:
    algorithm: ${JWT_ALGORITHM:RS256}
    secret: ${JWT_SECRET:dummy-dev-secret}
    public-key: ${JWT_PUBLIC_KEY:classpath:keys/public.pem}