server:
  port: 8080

spring:
  application:
    name: api-gateway

#Redis
  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
    gateway:
      routes:
        # ===============================
        # Eureka Dashboard UI
        # ===============================
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
          filters:
            - SetPath=/
        - id: eureka-sever-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        # ===============================
        # Auth Service Routes
        # ===============================
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**


management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
  instance:
    prefer-ip-address: true
    hostname: localhost

app:
  jwt:
    algorithm: RS256
    secret: 9WHfWmiB*k;&,s=M_b3rhs1T+izYVsAtX|@-!kW;iVU
    public-key: classpath:keys/public.pem