package com.payflowx.payment.constant;

public enum ErrorCode {

    INVALID_REQUEST,

    PAYMENT_NOT_FOUND,
    PAYMENT_ALREADY_SUCCESSFUL,
    PAYMENT_ALREADY_FAILED,
    PAYMENT_EXPIRED,
    PAYMENT_NOT_REFUNDABLE,

    INVALID_PAYMENT_STATE_TRANSITION,
    PAYMENT_AMOUNT_MISMATCH,
    PAYMENT_METHOD_NOT_SUPPORTED,

    DUPLICATE_PAYMENT_REQUEST,
    INVALID_IDEMPOTENCY_KEY,
    INVALID_IDEMPOTENCY_REQUEST,

    REFUND_NOT_FOUND,
    REFUND_AMOUNT_EXCEEDED,

    INTERNAL_SERVER_ERROR,
    ORDER_NOT_FOUND,
    ORDER_ALREADY_PAID,
    ORDER_EXPIRED,
    ORDER_CANCELLED,

    PAYMENT_CURRENCY_MISMATCH,
    ORDER_PAYMENT_UPDATE_FAILED,
    IDEMPOTENCY_REPLAY_DETECTED,
    PAYMENT_ATTEMPT_NOT_FOUND,
    INVALID_PAYMENT_STATUS,
    MERCHANT_NOT_FOUND
}